bank:
  start_budget: 15000
  start_useful_budget: 0.25
  start_VAT: 0.10
  start_deposit_percent: 0.05
license:
  market_license_price: 1500
  trade_license_price: 500
  loan_license_price: 10000
  loan_history_license_price: 20000
npc:
  trader_cost: 3500
  loaner_cost: 20000
town:
  start_useful_budget: 0.35
  start_useful_storage: 0.30
  start_vat: 0.05
ui:
  language: "EN"
  loc4bank: "C:\Users\j1sk1ss\Desktop\pServer\plugins\MenuFramework\bank_loc.txt"
  loc4lic: "C:\Users\j1sk1ss\Desktop\pServer\plugins\MenuFramework\license_loc.txt"
  loc4mayor: "C:\Users\j1sk1ss\Desktop\pServer\plugins\MenuFramework\mayor_loc.txt"
  loc4trader: "C:\Users\j1sk1ss\Desktop\pServer\plugins\MenuFramework\trader_loc.txt"
currency:
  name:
    raw: "Алеф"
    is: "Алеф"
    rs: "Алефа"
    ds: "Алефу"
    vs: "Алеф"
    ts: "Алефом"
    ps: "Алефе"
    ip: "Алефы"
    rp: "Алефов"
    dp: "Алефам"
    vp: "Алефы"
    tp: "Алефами"
    pp: "Алефах"
  sigh: "$"
