name: PcConomy
version: '${project.version}'
main: economy.pcconomy.PcConomy
api-version: '1.20'
authors: [ j1sk1ss ]
description: Main economy plugin for Potolot Craft made by j1sk1ss
website: https://potolotcraft.net


commands:
  take_cash:
    usage: /take_cash [amount]
  create_cash:
    usage: /create_cash [amount]
  create_wallet:
    usage: /create_wallet
  create_shareholder:
    usage: /create_shareholder
  reload_towns:
    usage: /reload_towns
  put_cash2bank:
    usage: /put_cash2bank [amount]
  create_banker:
    usage: /create_banker
  create_loaner:
    usage: /create_loaner
  create_npc_loaner:
    usage: /create_npc_loaner
  create_trader:
    usage: /create_trader
  create_npc_trader:
    usage: /create_npc_trader
  create_licensor:
    usage: /create_licensor
  switch_town2npc:
    usage: /switch_town2npc
  switch_town2player:
    usage: /switch_town2player
  town_menu:
    usage: /town_menu
  add_trade2town:
    usage: /add_trade2town [town name] [material] [amount]
  reload_npc:
    usage: /reload_npc
  full_info:
    usage: /full_info
  set_day_bank_budget:
    usage: /set_day_bank_budget [amount]
  transfer_share:
    usage: /transfer_share [town name] [player name] [shares count]
  shares_rate:
    usage: /shares_rate
  global_market_prices:
    usage: /global_market_prices


bank:
  start_budget: 15000
  start_useful_budget: 0.25
  start_VAT: 0.10
  start_deposit_percent: 0.05
license:
  market_license_price: 1200
  trade_license_price: 500
  loan_license_price: 3200
  loan_history_license_price: 1600
npc:
  trader_cost: 3000
  loaner_cost: 4500
town:
  start_useful_budget: 0.35
  start_useful_storage: 0.30
  start_vat: 0.05

