name: PcConomy
version: '${project.version}'
main: economy.pcconomy.PcConomy
api-version: 1.16
authors: [ PC_Java_Team ]
description: Main economy plugin for Potolot Craft
website: https://potolotcraft.net
