name: PcConomy
version: '${project.version}'
main: economy.pcconomy.PcConomy
api-version: 1.16
authors: [ j1sk1ss ]
description: Main economy plugin for Potolot Craft made by j1sk1ss
website: https://potolotcraft.net

commands:
  take_cash:
    usage: /take_cash
  create_cash:
    usage: /create_cash
  reload_towns:
    usage: /reload_towns
  save_data:
    usage: /save_data
  put_cash_to_bank:
    usage: /put_cash_to_bank
  create_banker:
    usage: /create_banker
  create_loaner:
    usage: /create_loaner
  create_npc_loaner:
    usage: /create_npc_loaner
  create_trader:
    usage: /create_trader
  create_npc_trader:
    usage: /create_npc_trader
  create_licensor:
    usage: /create_licensor
  switch_town_to_npc:
    usage: /switch_town_to_npc
  town_menu:
    usage: /town_menu
  add_trade_to_town:
    usage: /add_trade_to_town
  reload_npc:
    usage: /reload_npc
  full_info:
    usage: /full_info
  set_day_bank_budget:
    usage: /set_day_bank_budget

bank:
  start_budget: 15000
  start_useful_budget: 0.25
  start_VAT: 0.10
license:
  market_license_price: 1200
  trade_license_price: 500
  loan_license_price: 3200
  loan_history_license_price: 1600
npc:
  trader_cost: 3000
  loaner_cost: 4500
town:
  start_useful_budget: 0.35
  start_useful_storage: 0.30

