name: PcConomy
version: '${project.version}'
main: economy.pcconomy.PcConomy
api-version: '1.20'
authors: [ j1sk1ss ]
description: Main economy plugin for Potolot Craft made by j1sk1ss
website: https://potolotcraft.net


commands:
  take_cash:
    usage: /take_cash [amount]
    description: take cash from inventory (Without bank)
  create_cash:
    usage: /create_cash [amount]
    description: create cash and put to inventory (Without bank)
  create_wallet:
    usage: /create_wallet
    description: create empty wallet
  create_shareholder:
    usage: /create_shareholder
    description: create shareholder npc
  reload_towns:
    usage: /reload_towns
  put_cash2bank:
    usage: /put_cash2bank [amount]
    description: take moneys from inventory and put it to the bank (Moved to your bank account)
  create_banker:
    usage: /create_banker
    description: create banker npc
  create_npc_loaner:
    usage: /create_npc_loaner
    description: create loaner npc
  create_trader:
    usage: /create_trader
    description: create trader npc (Trading between players)
  create_npc_trader:
    usage: /create_npc_trader
    description: create trader npc (Trading between players and npc towns)
  create_licensor:
    usage: /create_licensor
    description: create licensor npc
  switch_town2npc:
    usage: /switch_town2npc
  switch_town2player:
    usage: /switch_town2player
  town_menu:
    usage: /town_menu
    description: open mayor menu
  add_trade2town:
    usage: /add_trade2town [town name] [material] [amount]
  reload_npc:
    usage: /reload_npc
  full_info:
    usage: /full_info
  set_day_bank_budget:
    usage: /set_day_bank_budget [amount]
    description: set budget that`s can be used by players in global bank
  shares_rate:
    usage: /shares_rate
    description: get summary prices for all shares on market
  global_market_prices:
    usage: /global_market_prices
    description: get summary prices of goods


bank:
  start_budget: 15000
  start_useful_budget: 0.25
  start_VAT: 0.10
  start_deposit_percent: 0.05
license:
  market_license_price: 1500
  trade_license_price: 500
  loan_license_price: 10000
  loan_history_license_price: 20000
npc:
  trader_cost: 3500
  loaner_cost: 20000
town:
  start_useful_budget: 0.35
  start_useful_storage: 0.30
  start_vat: 0.05

